#!/bin/bash
# Script to remove AI attributions from git commit messages
#
# This script uses git filter-branch to rewrite commit history and remove:
# - Co-Authored-By lines (especially for AI tools like Claude, Anthropic, Cursor, Warp, Copilot)
# - References to AI assistants, bots, or automated tools
# - Mentions of Claude, Cursor, Warp, GitHub Copilot, or similar AI tools
# - "Generated by" or "Created with" attributions
#
# WARNING: This rewrites git history. Use with caution!

set -e

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${YELLOW}================================================${NC}"
echo -e "${YELLOW}Git Commit Message Cleaner${NC}"
echo -e "${YELLOW}================================================${NC}"
echo ""
echo "This script will rewrite commit history to remove AI attributions."
echo ""
echo -e "${RED}WARNING: This modifies git history!${NC}"
echo "- All commit SHAs will change"
echo "- If already pushed, you'll need to force push"
echo "- Collaborators will need to reset their branches"
echo ""

# Get the branch name or commit range
BRANCH_OR_RANGE="${1:-HEAD}"

if [ "$BRANCH_OR_RANGE" = "HEAD" ]; then
    echo "Will process: Current branch from first commit to HEAD"
else
    echo "Will process: $BRANCH_OR_RANGE"
fi

echo ""
read -p "Do you want to continue? (yes/no): " -r
echo ""

if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    echo "Aborted."
    exit 0
fi

echo "Creating backup branch..."
BACKUP_BRANCH="backup-before-cleanup-$(date +%Y%m%d-%H%M%S)"
git branch "$BACKUP_BRANCH"
echo -e "${GREEN}✓${NC} Created backup branch: $BACKUP_BRANCH"
echo ""

echo "Rewriting commit messages..."

# Create a filter script
FILTER_SCRIPT=$(mktemp)
cat > "$FILTER_SCRIPT" << 'FILTER_EOF'
#!/bin/bash
# Read the commit message
msg=$(cat)

# Process line by line and filter out AI attributions
echo "$msg" | while IFS= read -r line || [ -n "$line" ]; do
    # Skip Co-Authored-By lines that mention AI tools or bots
    if echo "$line" | grep -qiE "^Co-Authored-By:.*\b(claude|anthropic|cursor|warp|copilot|bot|ai|assistant|automated)\b"; then
        continue
    fi
    
    # Skip Co-authored-by lines (case variations)
    if echo "$line" | grep -qiE "^Co-authored-by:.*\b(claude|anthropic|cursor|warp|copilot|bot|ai|assistant|automated)\b"; then
        continue
    fi
    
    # Skip lines with "Generated by" or "Created with" followed by AI tools
    if echo "$line" | grep -qiE "^\s*(Generated by|Created with|Authored by|Assisted by).*\b(claude|anthropic|cursor|warp|copilot|ai|assistant|bot)\b"; then
        continue
    fi
    
    # Skip lines that are purely AI tool attributions
    if echo "$line" | grep -qiE "^\s*(Claude|Anthropic|Cursor|Warp|GitHub Copilot|Copilot)\s*(generated|created|assisted|authored)"; then
        continue
    fi
    
    # Keep the line
    echo "$line"
done
FILTER_EOF

chmod +x "$FILTER_SCRIPT"

# Run git filter-branch
git filter-branch --msg-filter "$FILTER_SCRIPT" --force "$BRANCH_OR_RANGE"

# Clean up
rm "$FILTER_SCRIPT"

echo ""
echo -e "${GREEN}✓${NC} Commit messages cleaned successfully!"
echo ""
echo "Summary:"
echo "- Backup branch created: $BACKUP_BRANCH"
echo "- Commit history has been rewritten"
echo ""
echo "Next steps:"
echo ""
echo "1. Review the changes:"
echo "   git log --oneline"
echo "   git show <commit-sha>"
echo ""
echo "2a. If you're happy with the changes and want to push to remote:"
echo "    ${YELLOW}git push --force-with-lease origin $(git branch --show-current)${NC}"
echo ""
echo "2b. If you want to undo these changes:"
echo "    git reset --hard $BACKUP_BRANCH"
echo "    git branch -D $BACKUP_BRANCH"
echo ""
echo -e "${RED}IMPORTANT:${NC} If you force push, notify all collaborators!"
echo "They will need to reset their branches with:"
echo "  git fetch origin"
echo "  git reset --hard origin/$(git branch --show-current)"
